name: Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Database Migration
      run: php artisan migrate
